name: Compile, Upload and Release Typst Documents
on:
  workflow_dispatch:
  push:
    tags:
    - '**'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Insall Typst Compiler
      uses: baptiste0928/cargo-install@v3
      with:
        crate: typst
        version: '^0.12' # You can specify any semver range
    - name: Compile Typst
      run: typst compile ./publication/main.typ ./publication/bt-query-by-graph.pdf
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: '**/*.pdf'
    - name: Release on tag
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        name: "${{ github.ref_name }}"
        files: |
          ./publication/bt-query-by-graph.pdf
